@hostname = localhost
@port = 8000
@host = {{hostname}}:{{port}}



### get all todos
GET  http://{{host}}/api/todo/


### create a todo
POST http://{{host}}/api/todo/
content-type: application/json

{
    "title": "create api 911",
    "state": "inprogress",
    "endDate": 0
}

### Update todo state
PATCH http://{{host}}/api/todo/60d0df52cc48b0279797728/todo


### delete a todo 
DELETE  http://{{host}}/api/todo/60d0df0f5b776c27634db32




